
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: manageuser_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=am@700511
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P am@700511 -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manageuser_api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserManagementConnection=Server=sqlserver,1433;Database=UserManagementDB;User Id=sa;Password=am@700511;TrustServerCertificate=True;Encrypt=False
    ports:
      - "8080:8080"

volumes:
  sql_data:
